export declare function makeSprite(pixels: string, width: number, height: number, palette: string[]): HTMLCanvasElement;
export declare const sweetie16: number[];
export declare function sw16index(n: number): number;
export declare function for2d(width: number, height: number, func: Function): void;
export declare function for1d(max: number, func: Function): void;
export declare function srand(a: number): Function;
export declare function rgb(r: number, g: number, b: number): number;
export declare function mod(x: number, y: number): number;
export declare function makeGrid(width: number, height: number, default_?: any): any[][];
export declare function clamp(bottom: number, top: number, x: number): number;
